/**
 * WhatsApp Meta OAuth Callback
 *
 * Handles the redirect from Meta after user authorization.
 * State is HMAC-verified to prevent CSRF.
 */

import { NextRequest, NextResponse } from 'next/server';
import { db } from '@/lib/database';
import { createHmac, timingSafeEqual } from 'crypto';

const META_APP_ID = process.env.NEXT_PUBLIC_APP_ID;
const META_APP_SECRET = process.env.FACEBOOK_APP_SECRET;
const META_API_VERSION = 'v22.0';

interface StatePayload {
  shopId: string;
  timestamp: number;
}

function verifyAndDecodeState(state: string): StatePayload | null {
  try {
    const secret = process.env.FACEBOOK_APP_SECRET;
    if (!secret) return null;

    const raw = Buffer.from(state, 'base64url').toString();
    const { payload: payloadJson, sig } = JSON.parse(raw);

    const expectedSig = createHmac('sha256', secret).update(payloadJson).digest('hex');
    // Constant-time comparison
    if (
      sig.length !== expectedSig.length ||
      !timingSafeEqual(Buffer.from(sig), Buffer.from(expectedSig))
    ) {
      return null;
    }

    return JSON.parse(payloadJson) as StatePayload;
  } catch {
    return null;
  }
}

export async function GET(req: NextRequest) {
  try {
    const searchParams = req.nextUrl.searchParams;
    const code = searchParams.get('code');
    const state = searchParams.get('state');
    const error = searchParams.get('error');
    const errorDescription = searchParams.get('error_description');

    if (error === 'access_denied') {
      console.log('[WhatsApp Callback] User denied access:', errorDescription);
      return NextResponse.redirect(
        new URL('/dashboard/settings?tab=whatsapp&error=access_denied', req.url)
      );
    }

    if (!code || !state) {
      return NextResponse.redirect(
        new URL('/dashboard/settings?tab=whatsapp&error=invalid_response', req.url)
      );
    }

    // Verify HMAC signature — rejects any state not generated by our server
    const decoded = verifyAndDecodeState(state);
    if (!decoded) {
      return NextResponse.redirect(
        new URL('/dashboard/settings?tab=whatsapp&error=invalid_state', req.url)
      );
    }

    // Check state expiration (30 minutes)
    if (Date.now() - decoded.timestamp > 30 * 60 * 1000) {
      return NextResponse.redirect(
        new URL('/dashboard/settings?tab=whatsapp&error=expired_state', req.url)
      );
    }

    const shop = await db.shop.findUnique({
      where: { id: decoded.shopId },
      select: { id: true, name: true },
    });

    if (!shop) {
      return NextResponse.redirect(
        new URL('/dashboard/settings?tab=whatsapp&error=shop_not_found', req.url)
      );
    }

    // Must match exactly the redirect_uri used in /connect — Meta validates this.
    // Using the Host header here would let an attacker force a different redirect.
    const appUrl = process.env.NEXT_PUBLIC_APP_URL;
    if (!appUrl) {
      return NextResponse.redirect(
        new URL('/dashboard/settings?tab=whatsapp&error=server_config', req.url)
      );
    }
    const callbackUrl = `${appUrl.replace(/\/$/, '')}/api/whatsapp/callback`;

    // Exchange code for access token
    const tokenUrl = new URL('https://graph.facebook.com/v22.0/oauth/access_token');
    tokenUrl.searchParams.set('client_id', META_APP_ID!);
    tokenUrl.searchParams.set('client_secret', META_APP_SECRET!);
    tokenUrl.searchParams.set('redirect_uri', callbackUrl);
    tokenUrl.searchParams.set('code', code);

    const tokenRes = await fetch(tokenUrl.toString());
    if (!tokenRes.ok) {
      const errorData = await tokenRes.json().catch(() => ({}));
      console.error('[WhatsApp Callback] Token exchange failed:', errorData);
      throw new Error('Failed to exchange authorization code');
    }

    const tokenData = await tokenRes.json();
    const accessToken: string = tokenData.access_token;

    // Fetch user's WhatsApp Business accounts
    const wabasRes = await fetch(
      `https://graph.facebook.com/${META_API_VERSION}/me/accounts?access_token=${accessToken}`
    );
    const wabasData = await wabasRes.json();

    if (!wabasData.data || wabasData.data.length === 0) {
      return NextResponse.redirect(
        new URL('/dashboard/settings?tab=whatsapp&error=no_waba_found', req.url)
      );
    }

    const waba = wabasData.data[0];
    const wabaId: string = waba.id;

    const phonesRes = await fetch(
      `https://graph.facebook.com/${META_API_VERSION}/${wabaId}/phone_numbers?access_token=${accessToken}`
    );
    const phonesData = await phonesRes.json();

    if (!phonesData.data || phonesData.data.length === 0) {
      return NextResponse.redirect(
        new URL('/dashboard/settings?tab=whatsapp&error=no_phone_found', req.url)
      );
    }

    const phone = phonesData.data[0];

    await db.shop.update({
      where: { id: shop.id },
      data: {
        whatsappProvider: 'META',
        metaAccessToken: accessToken,
        metaPhoneNumberId: phone.id,
        metaBusinessAccountId: wabaId,
        whatsappPhoneNumber: phone.phone_number,
        whatsappEnabled: true,
      },
    });

    console.log(`[WhatsApp Callback] Connected ${shop.name} to WABA ${wabaId}`);

    return NextResponse.redirect(
      new URL('/dashboard/settings?tab=whatsapp&success=connected', req.url)
    );
  } catch (error: any) {
    console.error('[WhatsApp Callback] Error:', error);
    return NextResponse.redirect(
      new URL(`/dashboard/settings?tab=whatsapp&error=${encodeURIComponent(error.message || 'connection_failed')}`, req.url)
    );
  }
}
